### PR TITLE
Facade: best solution to clean views

### PR DESCRIPTION
**Pull request by lcezermf**
As we talk about in https://github.com/internetsistemas/repense-asi/issues/237

### CODE REVIEW

**Comment by felipefontoura** [comment]
Awesome @lccezinha. @brunoocasali @felipebroering e @thiagodepaula ?

**Comment by felipefontoura** [comment]
@brunoocasali @felipebroering e @thiagodepaula ?

**Comment by brunoocasali** [comment]
Looks so good!! :+1:

**Comment by felipefontoura** [comment]
:coffee:

**Pull request merged**
