### PR TITLE
Add best practice of rails migrations

### PR DESCRIPTION
**Pull request by vgsantoniazzi**

### CODE REVIEW

**Comment by vgsantoniazzi** [comment]
I don't know if use of FK is good. It's validate only the '_id' value and nothing if the other table is the 'right' table

**Comment by vgsantoniazzi** [comment]
The best use is in the relationship model when you can explicit the foreign key

**Comment by vgsantoniazzi** [comment]
Just note: Added section to add missing foreign keys

**Comment by felipefontoura** [comment]
:+1:

**Pull request merged**
